# This is a basic workflow to help you get started with Actions
name: My first Workflow
# Controls when the action will run.
on: [push, pull_request]
  # Triggers the workflow on push or pull request events for all branches

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          
          - os: windows-latest
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"

    - name: Build with Maven
      run: mvn -B compile --file pom.xml

    - name: Run Tests
      run: mvn -B test --file pom.xml
